djangoherokuapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('herokuapp.urls')),
]

herokuapp/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('translate', views.search, name='search'),
    # path('detail', views.detail, name='detail'),
    # path('<int:request_id>/detail', views.detail, name='detail'),
    # path('<int:request_id>/step1', views.step1, name='step1'),
    # path('<int:request_id>/step2', views.step2, name='step2'),
    # path('<int:request_id>/step3', views.step3, name='step3'),
    # path('index.html', views.index, name='index.html'),
    # path('phuong', views.phuong, name='phuong'),
    # path('hien', views.hien, name='hien'),
    # path('hack', views.hack, name='hack'),
    # path('<int:request_id>/',views.detail, name='detail'),
    # path('<int:request_id>/result',views.result, name='result'), 
    # path('<int:request_id>/vote/<int:request_id1>',views.vote, name='vote'),
    # path('<int:pk>/detail',views.testGenericView.as_view(), name='detail'),
]

herokuapp/models.py
from django.db import models

# Create your models here.
# https://docs.djangoproject.com/en/2.2/ref/models/fields/

class User(models.Model):
    id = models.AutoField
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    phone = models.IntegerField(default=0)
    address = models.CharField(max_length=200)

    def phuong(self):
        return self.username

herokuapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import User
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.views import generic
import requests   
from django.views.decorators.csrf import csrf_exempt  

# Create your views here.
 
 
def index(request):
    return render(request, "home/index.html", {"users": 1})

@csrf_exempt
def search(request):
    
    fromLocation = ''
    try:
        fromLocation = request.POST['cauHoi']
    except (KeyError):
        # Redisplay the question voting form.
        param = {
            "cauHoi": '',
            "traLoi": '', 
        }
        return render(request, "home/chat.html", param)
    
    # translate
    param = {
        "cauHoi": fromLocation,
        "traLoi": ApiTranslate.translate(fromLocation)[:-5], 
    } 
 
    return render(request, "home/chat.html", param)


# def detail(request, request_id):
#     print(request_id)
#     return render(request, "home/chi-tiet-xe.html", {"id": request_id})


# def step1(request, request_id):
#     print(request_id)
#     return render(request, "home/dat-ve-buoc-1.html", {"id": request_id})

# def step2(request, request_id):
#     print(request_id)
#     return render(request, "home/dat-ve-buoc-2.html", {"id": request_id})

# def step3(request, request_id):
#     print(request_id)
#     return render(request, "home/dat-ve-buoc-3.html", {"id": request_id})


# def index(request):
#     users = User.objects.order_by('username')[:3]
#     output = '<br>'.join(['Hello %s <a href="phuong">%s</a>' %
#                           (u.username, u.address) for u in users])
#     return HttpResponse('Hello Lê Hồng Phương <a href="phuong">adf</a>')


# def phuong(request):
#     users = User.objects.all()
#     template = loader.get_template('home/index.html')
#     context = {
#         'users': users,
#     }

#     return HttpResponse(template.render(context, request))
#     # return HttpResponse('Phuong method <a href="/home/">adf</a>')


# def hien(request):
#     users = User.objects.all()
#     context = {
#         'users': users,
#     }
#     username = request.POST['username']
#     password = request.POST['password']
#     print(username)
#     # return render(request, 'home/index.html', context)
#     # return HttpResponse("username %s password %s" %(username,password))
#     # return HttpResponse("username %s password %s" %(username,password))
#     return HttpResponseRedirect(reverse("home:index"))


# def hack(request):
#     # URL = "https://www.vetaulyson.com/?component=tim-kiem&act=search&type=oneway&khoihanh=sa-ky&diemden=ly-son&date_kh=28-04-2019&soluong_start=2&date_ve=&soluong_return=0&btnBooking=T%C3%8CM+V%C3%89+NGAY"
#     # URL = "https://www.vetaulyson.com/"
#     # location given here
#     # location = "delhi technological university"

#     # defining a params dict for the parameters to be sent to the API
#     # PARAMS = {'address': location}

#     # sending get request and saving the response as response object
#     # for x in range(2):
#     # requests.post(url=URL, params={})
#     for x in range(5000):
#         requests.get('https://www.vetaulyson.com/')

#     # extracting data in json format
#     # data = r.json()

#     # print("phuong" + req.url)

#     return render(request, "home/hack.html", {})


# def detail(request, request_id):
#     return HttpResponse('detail %s' % request_id)


# def result(request, request_id):
#     response = "result %s"
#     return HttpResponse(response % request_id)


# def vote(request, request_id, request_id1):
#     return HttpResponse("vote %s + %s = %s" % (request_id, request_id1, (request_id+request_id1)))


# def testRaise(request):
#     u = get_object_or_404(User, pk=12312)
#     return render(request, "home/index.html", {"users": u})


# class testGenericView(generic.DetailView):
#     model = User
#     template_name = 'home/detail.html'



# deep learning begin
# from __future__ import unicode_literals, print_function, division
import torch

from core_translate.Encoder import EncoderRNN
from core_translate.AttnDecoder import AttnDecoderRNN
from core_translate.ultis import prepareData, evaluate

use_cuda = torch.cuda.is_available()

MAX_LENGTH = 50

TRANSLATION = "eng-vn"
input_lang, output_lang, pairs = prepareData(TRANSLATION.split("-")[0],
                                             TRANSLATION.split('-')[1])

teacher_forcing_ratio = 0.5
hidden_size = 256
encoder1 = EncoderRNN(input_lang.n_words, hidden_size)
attn_decoder1 = AttnDecoderRNN(hidden_size, output_lang.n_words,
                               1, dropout_p=0.1)
if use_cuda:
    encoder1 = encoder1.cuda()
    attn_decoder1 = attn_decoder1.cuda()


encoder1.load_state_dict(torch.load("core_translate/nmt_model/%s_encoder1.pth.tar"%TRANSLATION, map_location={'cuda:0': 'cpu'}))
encoder1.eval()

attn_decoder1.load_state_dict(torch.load("core_translate/nmt_model/%s_attn_decoder1.pth.tar"%TRANSLATION, map_location={'cuda:0': 'cpu'}))
attn_decoder1.eval()

class ApiTranslate:
    @staticmethod
    def translate(input_sentence=""):
        output_words, attentions = evaluate(input_lang, output_lang, encoder1, attn_decoder1, input_sentence)
        return ' '.join(output_words)

    @staticmethod
    def init():
        input_sentence = "i love you"
        print("Input Sentence: ", input_sentence)
        output_words, attentions = evaluate(input_lang, output_lang, encoder1, attn_decoder1, input_sentence)
        print("Output Sentence:", ' '.join(output_words))
# deep learning end 

herokuapp/templates/home/chat.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <title>We Pos Translate Chat Bot</title>
    <base href="/">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- STYLES -->
    <!-- <link rel='stylesheet' id='compiled.css-css' href='assets/mdbootstrap/style.css' type='text/css' media='all' />
  <link rel='stylesheet' id='compiled.css-css' href='assets/mdbootstrap/compiled-4.8.2.min.css' type='text/css' media='all' /> -->

    <link rel='stylesheet' id='wsl-widget-css'
        href='https://mdbootstrap.com/wp-content/plugins/wordpress-social-login/assets/css/style.css?ver=5.2.1'
        type='text/css' media='all' />
    <link rel='stylesheet' id='compiled.css-css'
        href='https://mdbootstrap.com/wp-content/themes/mdbootstrap4/css/compiled-4.8.2.min.css?ver=4.8.2'
        type='text/css' media='all' />
</head>

<body>

    <!-- Card -->
    <div class="card text-center">
        <!-- Card content -->
        <div class="card-body">

            <!-- Title -->
            <h4 class="card-title font-weight-bold">WE POS TRANSLATE CHAT BOT WITH HACKERTHON</h4>
            <form action="{% url 'home:search' %}" method="POST">
                {% csrf_token %}
                <input type="text" name="cauHoi" class="form-control" placeholder="Please input here PinkWays" required>
  
                <p>Ask: {{cauHoi}}</p>
                <p>Reply: {{traLoi}}</p>
                

                <div class="text-center">
                    <button class="btn btn-primary" type="submit">TRANSLATE</button>
                </div>
            </form>
        </div>

    </div>
    <!-- Card -->
</body>

</html>

herokuapp/templates/home/dat-ve-buoc-2.html
<!DOCTYPE html>
<html class="load-full-screen">
<head>
	
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="LimpidThemes">
	
	<title>Cruise - Responsive Travel Agency Template</title>
	
    <!-- STYLES -->
	<link href="/static/home/assets/css/animate.min.css" rel="stylesheet">
	<link href="/static/home/assets/css/bootstrap-select.min.css" rel="stylesheet">
	<link href="/static/home/assets/css/owl.carousel.css" rel="stylesheet">
	<link href="/static/home/assets/css/owl-carousel-theme.css" rel="stylesheet">
    <link href="/static/home/assets/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="/static/home/assets/css/flexslider.css" rel="stylesheet" media="screen">
	<link href="/static/home/assets/css/style.css" rel="stylesheet" media="screen">
	<!-- LIGHT -->
	<link rel="stylesheet" type="text/css" href="/static/home/assets/css/dummy.css" id="select-style">
	<!-- <link href="/static/home/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet"> -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	
	<link href="/static/home/assets/css/light.css" rel="stylesheet" media="screen">
	
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,800,700,600' rel='stylesheet' type='text/css'>

</head>
<body class="load-full-screen">

<!-- BEGIN: PRELOADER -->
<div id="loader" class="load-full-screen">
	<div class="loading-animation">
		<span><i class="fa fa-plane"></i></span>
		<span><i class="fa fa-bed"></i></span>
		<span><i class="fa fa-ship"></i></span>
		<span><i class="fa fa-suitcase"></i></span>
	</div>
</div>
<!-- END: PRELOADER -->

<!-- BEGIN: SITE-WRAPPER -->
<div class="site-wrapper">
	
<!-- BEGIN: NAV SECTION -->
<section>
	<div class="row transparent-menu-top">
		<div class="container clear-padding">
			<div class="navbar-contact">
				<div class="col-md-7 col-sm-6 clear-padding">
					<a href="#" class="transition-effect"><i class="fa fa-phone"></i> (+91) 1234567890</a>
					<a href="#" class="transition-effect"><i class="fa fa-envelope-o"></i> support@email.com</a>
				</div>
				<div class="col-md-5 col-sm-6 clear-padding search-box">
					<div class="col-md-6 col-xs-5 clear-padding">
					</div>
					<div class="col-md-6 col-xs-7 clear-padding user-logged">
						<a href="#" class="transition-effect">
							<img src="/static/home/assets/images/user.jpg" alt="cruise">
							Hi, Lenore
						</a>
						<a href="#" class="transition-effect">
							<i class="fa fa-sign-out"></i>Sign Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="clearfix"></div>
	<div class="row transparent-menu">
		<div class="container clear-padding">
			<!-- BEGIN: HEADER -->
			<div class="navbar-wrapper">
				<div class="navbar navbar-default" role="navigation">
					<!-- BEGIN: NAV-CONTAINER -->
					<div class="nav-container">
						<div class="navbar-header">
							<!-- BEGIN: TOGGLE BUTTON (RESPONSIVE)-->
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>						
							<!-- BEGIN: LOGO -->
							<a class="navbar-brand logo" href="/home">BLABLACAR</a>
						</div>
						
						<!-- BEGIN: NAVIGATION -->       
						<div class="navbar-collapse collapse">
							<ul class="nav navbar-nav navbar-right">
								<li><a class="transition-effect" href="#">Trang Chủ</a></li>
								<li><a class="transition-effect" href="#"></i>Giới Thiệu</a></li>
								<li><a class="transition-effect" href="#"></i>Tìm xe</a></li>
								<li><a class="transition-effect" href="#"></i>Liên hệ</a></li>
								<li><a class="transition-effect" href="#"></i>Đăng ký</a></li>
							</ul>
						</div>
						<!-- END: NAVIGATION -->
					</div>
					<!--END: NAV-CONTAINER -->
				</div>
			</div>
			<!-- END: HEADER -->
		</div>
	</div>
</section>
<!-- END: NAV SECTION -->
	<!-- START: PAGE TITLE -->
	<div class="row page-title">
		<div class="container clear-padding text-center flight-title">
			<h3>Your Selection</h3>
			<h4><i class="fa fa-plane"></i>NEW DELHI<i class="fa fa-long-arrow-right"></i>NEW YORK</h4>
			<span><i class="fa fa-calendar"></i> 05 Aug <i class="fa fa-male"></i>Traveller(s) - 2 Adult</span>
		</div>
	</div>
	<!-- END: PAGE TITLE -->
	
	<!-- START: BOOKING TAB -->
	<div class="row booking-tab">
		<div class="container clear-padding">
			<ul class="nav nav-tabs">
				<li class="active col-md-4 col-sm-4 col-xs-4"><a class="text-center"><i class="fa fa-edit"></i><span>Kiểm tra giỏ hàng</span></a></li>
				<li class="active col-md-4 col-sm-4 col-xs-4"><a class="text-center"><i class="fa fa-male"></i><span>Điền thông tin</span></a></li>
				<li class="col-md-4 col-sm-4 col-xs-4"><a class="text-center"><i class="fa fa-check-square"></i> <span>Thanh toán</span></a></li>
			</ul>
		</div>
	</div>
	<div class="row booking-detail">
		<div class="container clear-padding">
			<div class="">
				<div class="">
					<div class="col-md-8 col-sm-8">
						<div class="passenger-detail">
							<h3>Passenger Details</h3>
							<div class="passenger-detail-body">
								<form action="{% url 'home:step3' id %}" method="POST">
									{% csrf_token %}
									<div class="col-md-6 ol-sm-6">
										<label>First Name</label>
										<input type="text" name="firstname" required class="form-control">
									</div>
									<div class="col-md-6 ol-sm-6">
										<label>Last Name</label>
										<input type="text" name="lastname" required class="form-control">
									</div>
									<div class="col-md-6 ol-sm-6">
										<label>Email</label>
										<input type="email" name="email" required class="form-control">
									</div>
									<div class="col-md-6 ol-sm-6">
										<label>Verify Email</label>
										<input type="email" name="verifyEmail" class="form-control">
									</div>
									<div class="col-md-6 ol-sm-6">
										<label>Country Code</label>
										<select name="countryCode" class="form-control">
											<option>+84 Vietnam</option>
											<option>+1 United States</option>
											<option>+1 Canada</option>
											<option>+44 United Kingdom</option>
											<option>+91 India</option>
										</select>
									</div>
									<div class="col-md-6 ol-sm-6">
										<label>Phone Number</label>
										<input type="number" name="phoneNumber" class="form-control" required>
									</div>
									<div class="col-md-12">
										<label><input type="checkbox" name="alert"> Send me newsletters and updates</label>
									</div>
									<!-- SUBMIT BUTTON -->
									<div class="text-center">
										<button type="submit">CONTINUE <i class="fa fa-chevron-right"></i></button>
									</div> 
									 
								</form>
								<!-- <div class="text-center">
									<a  href="dat-ve-buoc-3.html"><button>CONTINUE <i class="fa fa-chevron-right"></i></button></a>
								</div> -->
							</div>
						</div>
						<div class="login-box">
							<h3>Sign In</h3>
							<div class="booking-form">
								<div class="col-md-6 col-sm-6">
									<form >
										<label>Email</label>
										<input class="form-control" type="email" name="emailid" placeholder="Enter Your Email" required>
										<label>Password</label>
										<input class="form-control" type="password" name="password" placeholder="Enter Password" required>
										<a href="#">Forget Password?</a>
										<label>Phone Number (Optional)</label>
										<input class="form-control" type="text" name="phone">
										<label><input type="checkbox" name="remember"> Remember me</label>
										<button type="submit">Login</button>
									</form>
								</div>
								<div class="col-md-6 col-sm-6 text-center">
									<div class="social-media-login">
										<a href="#"><i class="fa fa-facebook"></i>Log in With Facebook</a>
										<span>Or</span>
										<a href="#"><i class="fa fa-plus"></i>Create Account</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 col-sm-4 booking-sidebar">
						<div class="sidebar-item">
							<h4><i class="fa fa-bookmark"></i>Fare Details</h4>
							<div class="sidebar-body">
								<table class="table">
									<tr>
										<td>Adult 1</td>
										<td>$199</td>
									</tr>
									<tr>
										<td>Base Fare</td>
										<td>$100</td>
									</tr>
									<tr>
										<td>Service Fee</td>
										<td>$50</td>
									</tr>
									<tr>
										<td>Airport Taxes</td>
										<td>$20</td>
									</tr>
									<tr>
										<td>You Pay</td>
										<td class="total">$500</td>
									</tr>
								</table>
							</div>
						</div>
						<div class="sidebar-item contact-box">
							<h4><i class="fa fa-phone"></i>Need Help?</h4>
							<div class="sidebar-body text-center">
								<p>Need Help? Call us or drop a message. Our agents will be in touch shortly.</p>
								<h2>+91 1234567890</h2>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
<!-- START: FOOTER -->
<section id="footer">
	<footer>
		<div class="row main-footer-sub">
			<div class="container clear-padding">
				<div class="col-md-7 col-sm-7">
					<form >
						<label>SUBSCRIBE TO OUR NEWSLETTER</label>
						<div class="clearfix"></div>
						<div class="col-md-9 col-sm-8 col-xs-6 clear-padding">
							<input class="form-control" type="email" required placeholder="Enter Your Email" name="email">
						</div>
						<div class="col-md-3 col-sm-4 col-xs-6 clear-padding">
							<button type="submit"><i class="fa fa-paper-plane"></i>SUBSCRIBE</button>
						</div>
					</form>
				</div>
				<div class="col-md-5 col-sm-5">
					<div class="social-media pull-right">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							<li><a href="#"><i class="fa fa-youtube"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="main-footer row">
			<div class="container clear-padding">
				<div class="col-md-3 col-sm-6 about-box">
					<h3>CRUISE</h3>
					<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
					<a href="#">READ MORE</a>
				</div>
				<div class="col-md-3 col-sm-6 links">
					<h4>Popular Tours</h4>
					<ul>
						<li><a href="#">Romantic France</a></li>
						<li><a href="#">Wonderful Lodnon</a></li>
						<li><a href="#">Awesome Amsterdam</a></li>
						<li><a href="#">Wild Africa</a></li>
						<li><a href="#">Beach Goa</a></li>
						<li><a href="#">Casino Los Vages</a></li>
						<li><a href="#">Romantic France</a></li>
					</ul>
				</div>
				<div class="clearfix visible-sm-block"></div>
				<div class="col-md-3 col-sm-6 links">
					<h4>Our Services</h4>
					<ul>
						<li><a href="#">Domestic Flights</a></li>
						<li><a href="#">International Flights</a></li>
						<li><a href="#">Tours & Holidays</a></li>
						<li><a href="#">Domestic Hotels</a></li>
						<li><a href="#">International Hotels</a></li>
						<li><a href="#">Cruise Holidays</a></li>
						<li><a href="#">Car Rental</a></li>
					</ul>
				</div>
				<div class="col-md-3 col-sm-6 contact-box">
					<h4>Contact Us</h4>
					<p><i class="fa fa-home"></i> Street #156 Burbank, Studio City Hollywood, California USA</p>
					<p><i class="fa fa-phone"></i> +91 1234567890</p>
					<p><i class="fa fa-envelope-o"></i> support@domain.com</p>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-12 text-center we-accept">
					<h4>We Accept</h4>
					<ul>
						<li><img src="/static/home/assets/images/card/mastercard.png" alt="cruise"></li>
						<li><img src="/static/home/assets/images/card/visa.png" alt="cruise"></li>
						<li><img src="/static/home/assets/images/card/american-express.png" alt="cruise"></li>
						<li><img src="/static/home/assets/images/card/mastercard.png" alt="cruise"></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="main-footer-nav row">
			<div class="container clear-padding">
				<div class="col-md-6 col-sm-6">
					<p>Copyright &copy; 2015 LimpidThemes. All Rights Reserved.</p>
				</div>
				<div class="col-md-6 col-sm-6">
					<ul>
						<li><a href="#">FLIGHTS</a></li>
						<li><a href="#">TOURS</a></li>
						<li><a href="#">CARS</a></li>
						<li><a href="#">HOTELS</a></li>
						<li><a href="#">BLOG</a></li>
					</ul>
				</div>
				<div class="go-up">
					<a href="#"><i class="fa fa-arrow-up"></i></a>
				</div>
			</div>
		</div>
	</footer>
</section>
<!-- END: FOOTER -->

</div>
<!-- END: SITE-WRAPPER -->

<!-- Load Scripts -->
<script src="/static/home/assets/js/respond.js"></script>
<script src="/static/home/assets/js/jquery.js"></script>
<script src="/static/home/assets/plugins/owl.carousel.min.js"></script>
<script src="/static/home/assets/js/bootstrap.min.js"></script>
<script src="/static/home/assets/js/jquery-ui.min.js"></script>
<script src="/static/home/assets/js/bootstrap-select.min.js"></script>
<script src="/static/home/assets/plugins/wow.min.js"></script>
<script src="/static/home/assets/js/js.js"></script>
</body>
</html>